[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Библиотеки
lib_deps = 
    milesburton/DallasTemperature@^3.9.0
    paulstoffregen/OneWire@^2.3.7
    adafruit/DHT sensor library@^1.4.4

; Настройки для ESP32
build_flags = 
    -DARDUINO_LOOP_STACK_SIZE=4096
    